String siteMain(){
  String HTML="";

  HTML+="<!DOCTYPE html>";
  HTML+="<html>";
  HTML+=" <head>";
  HTML+="<meta charset='utf-8'>";
  HTML+="<title>Setup</title>";
  HTML+="<style type='text/css'>";
  HTML+="body {";
  HTML+="font-family:arial;";
  HTML+="color: #D8DBE2;";
  HTML+="background-color: #599392;";
  HTML+="}";
  HTML+=".panelHead{";
  HTML+="margin-left: auto;";
  HTML+="margin-right: auto;";
  HTML+="margin-top: 30px;";
  HTML+="width:330px;";
  HTML+="height: auto;";
  HTML+="background-color: #125559;";
  HTML+="padding-left: 50px;";
  HTML+="padding-bottom: 50px;";
  HTML+="padding-top: 30px;";
  HTML+="border-radius: 6px;";
  HTML+="}";
  HTML+=".txtbox{";
  HTML+="border: 0px;";
  HTML+="height: 20px;";
  HTML+="background-color: #D8DBE2;";
  HTML+="color: #484A47;";
  HTML+="margin-top: 10px;";
  HTML+="margin-bottom: 10px;";
  HTML+="border-radius: 15px;";
  HTML+="}";
  HTML+=".btn{";
  HTML+="width: 70px;";
  HTML+="height: 30px;";
  HTML+="color: #484A47;";
  HTML+="background-color: #D8DBE2;";
  HTML+="border: 0;";
  HTML+="border-radius: 15px;";
  HTML+="}";
  HTML+="</style>";
  HTML+="</head>";
  HTML+="<body>";
  HTML+="<div class='panelHead'>";
  HTML+="<h1 class='titulo' align=center >Bem-vindo!</h1>";
  HTML+="<form>";
  HTML+="<table >";
  HTML+="<tr align=right>";
  HTML+="<td>SSID:</td>";
  HTML+="<td><input class='txtbox' type='text' required name='SIID' size='20' /></td>";
  HTML+="</tr>";
  HTML+="<tr align=right>";
  HTML+="<td>Senha:</td>";
  HTML+="<td><input class='txtbox' type='text' name='Pass' size='20' /></td>";
  HTML+="</tr>";
  HTML+="<tr align=right>";
  HTML+="<td>Server IP:</td>";
  HTML+="<td><input class='txtbox' type='text' required name='ServerIP' size='20' /></td>";
  HTML+="</tr>";
  HTML+="<tr align=right>";
  HTML+="<td>Porta:</td>";
  HTML+="<td><input class='txtbox' type='text' required name='Port' size='20' /></td>";
  HTML+="</tr>";
  HTML+="<tr align=right>";
  HTML+="<td>Identificador:</td>";
  HTML+="<td><input class='txtbox' type='text' required name='Ident' size='20' /></td>";
  HTML+="</tr>";
  HTML+="<tr align=right>";
  HTML+="<td></td>";
  HTML+="<td><input class='btn' type='submit' value='Enviar'></td>";
  HTML+="</tr>";
  HTML+="</table>";
  HTML+="</form>";
  HTML+="</div>";
  HTML+="</body>";
  HTML+="</html>";

  return HTML;
}

String siteResposta(){
  String HTML="";
  
  HTML+="<!DOCTYPE html>";
  HTML+="<html>";
  HTML+="<head>";
  HTML+="<title>Setup</title>";
  HTML+="<meta charset='utf-8'>";
  HTML+="<style type='text/css'>";
  HTML+="body {";
  HTML+="font-family:arial;";
  HTML+="color: #D8DBE2;";
  HTML+="background-color: #599392;";
  HTML+="}";
  HTML+=".titulo{";
  HTML+="margin-right: 15px;";
  HTML+="margin-left: 15px;";
  HTML+="}";
  HTML+=".panelHead{";
  HTML+="padding-top:30px;";
  HTML+="margin-left: auto;";
  HTML+="margin-right: auto;";
  HTML+="margin-top: 30px;";
  HTML+="width:400px;";
  HTML+="height: 200px;";
  HTML+="background-color: #125559;";
  HTML+="border-radius: 6px;";
  HTML+="}";
  HTML+="</style>";
  HTML+="</head>";
  HTML+="<body>";
  HTML+="<div class='panelHead'>";
  HTML+="<h1 class='titulo' align=Center>Configurado!</h1>";
  HTML+="<h3 class='titulo' align=center >Caso o painel não conecte-se a rede em alguns segundos, algo correu mal, resete o painel e tente novamente.</h3>";
  HTML+="</div>";
  HTML+="</body>";
  HTML+="</html>";
  
  return HTML;
}
